### ISSUE TITLE
Cite sources on Can I Vote page.

### ISSUE THREAD

**Issue by SchaeStewart** [codeforgso/GoVote#100]
## This is a: 

* [ ] bug
* [x] enhancement
* [ ] feature-discussion

# Enhancement
## Description

Cite the information the Can I Vote page.  Issues #85 and #99.

**Comment by tleisman** [comment]
All this information is accurate. I've also reformatted the copy and arranged it in a new google document here. This breaks up the text and makes it a little more accessible, and includes links to some images we could use to make it more user friendly. 

https://docs.google.com/document/d/1SiG2xfYQLY8LaXQXQKmTqkQcKen86OXd0D5KWLnYWk0/edit?usp=sharing
