### ISSUE TITLE
2019 Project Goals

### ISSUE THREAD

**Issue by SchaeStewart** [codeforgso/GoVote#122]
## This is a: 

* [ ] bug
* [ ] enhancement
* [x] feature-discussion

# Feature-Discussion
I am creating this issue as a place to document our goals for the next quarter. By the end of this quarter we hope to get the project to a logical stopping point. Since we do not yet have a community partner and there are no municipal elections in 2019, this seems like the best idea. The goals for this quarter are the following: 

## Make the project easier to fork  
- Create a global config file for things like city, city abbreviated, county, or anything that might change if another group or brigade forks the project for their area. See issue #123 
- Implement the config file by replacing references to Greensboro specific data with variables in the config file.
- Document any Greensboro Specific items that aren't easily replaceable. 

## Create content for Election Day page  
- Write copy for "What to Expect" section
- Write copy for "How to report issues with your polling place"
- Add the polling place lookup functionality. This already exists on the Where&When page so it just needs to be extracted to a reusable component and placed on both pages. See issue #121 

### Collect Candidate information
- NCSBE has a list available [here](https://www.ncsbe.gov/Portals/0/Documents/2018_General_Election_Candidate_List_with_Contacts_Updated_08212018.xlsx?ver=2018-08-21-165413-230). This is a good starting place but we want to add additional information.
- Specifically we want: website, facebook, twitter, linkedIn, and email for candidates that have such info.
  -  __Discussion question:__ is there any other information we want? #128 
- Use this [spreadsheet](https://docs.google.com/spreadsheets/d/1STCIuqDyw1a7wdtX929603SaMrnjuCmaDMujHdlR3IU/edit#gid=393871294) for tracking candidate info.

### Create way to store candidate information  
- I think the database is going to be the best place to put this info. We also need to store information about which office each candidate is running for and in which district as additional columns in the database.
- To deploy these changes to the production DB we may need to rebuild it.

### Create way to retrieve candidate information
- When a user visits the candidate page they will use the VoterRegLookup and we will display the candidates they can vote for.
- We have to create a second API endpoint to handle this.

### Display candidate info
- Using the returned candidate info we will display it to the user.
- __Discussion Question:__ Do we want to also have a list of all candidates for the county on this page?
- Generate some mock data so this feature can be worked on while the backend work is being done.
- Create some wireframes/mockups to give contributors and idea of what they should be building.

**Comment by zenlex** [comment]
This needs to be updated for 2020 or deleted.

**Comment by zenlex** [comment]
Closing for now. Can revisit after triage on 2020
