### ISSUE TITLE
Create config.js file

### ISSUE THREAD

**Issue by SchaeStewart** [codeforgso/GoVote#123]
## This is a: 

* [ ] bug
* [x] enhancement
* [ ] feature-discussion

# Enhancement
## Description
Create a config file for storing city and county specific variables. Start with the following items: city, city name abbreviated, county, app title (GoVoteGSO).

## Implementation
Create a `config.js` file in the `./src` directory.  
Export the variables mentioned above. Use `UPPER_SNAKE_CASE` since these are "global" variables.

**Comment by SchaeStewart** [comment]
In the long run it may be better to move this to a `.env` file, but for now this is the quickest and simplest solution so we'll use it.

**Comment by joshhazelhurst123** [comment]
hi @SchaeStewart I would like to create the config.js file. It sounds like creating a config.js file and declaring variables. Shall I create a pull request for this. Thanks. Example below.
var CITY; 
var CITY_NAME_ABBREVIATED; var COUNTRY; var APP_TITLE;

**Comment by SchaeStewart** [comment]
@joshhazelhurst123 Correct. Just use `const` instead of `var` and use `export` keyword to export the variables.

If you have any other questions, just ask me here, or you can ping me on [slack](https://bit.ly/cfgso-slack)

**Comment by joshhazelhurst123** [comment]
Thanks @SchaeStewart I have created a pull request for this #132

**Comment by zenlex** [comment]
Looks like this was closed and merged....
