### ISSUE TITLE
Configure docker-compose.yml to use .env file

### ISSUE THREAD

**Issue by SchaeStewart** [codeforgso/GoVote#126]
## This is a: 

* [ ] bug
* [x] enhancement
* [ ] feature-discussion

# Enhancement
## Description
Move the environment variables in the `docker-compose.yml` file to a .env file.  
See docker-compose env docs: https://docs.docker.com/compose/environment-variables/

## Implementation

- Move the environment variables that are hard coded in the `docker-compose.yml` file.
- Create a  `sample.env` file that has the same keys as the `.env` file. Check this into the repo.
- Add `.env` to `.gitignore`
- Update README with instructions on copying `sample.env` to `.env`.

**Comment by priyanka-ravi** [comment]
@SchaeStewart I'll do this for you guys real quick! :)

**Comment by SchaeStewart** [comment]
Awesome thanks!

If you have questions ping me on slack

https://bit.ly/cfgso-slack

Schaffer
