### ISSUE TITLE
Change fileName and url in etlj.js to an environment variable

### ISSUE THREAD

**Issue by SchaeStewart** [codeforgso/GoVote#127]
## This is a: 

* [ ] bug
* [x] enhancement
* [ ] feature-discussion

# Enhancement
## Description
In order to make the project more forkable the `fileName` and `url` variables in etl.js need to be changed to environment variables and added to the `.env` and `sample.env`

## Implementation

- Ensure the environment variable works properly with your local docker dev environment
- If the `.env` file does not exist yet, add the variable to the `docker-compose.yml` file under the govote.environement section.
- Update README

**Comment by SchaeStewart** [comment]
As a note to me or whoever merges this issue. We need to ensure that etl will still run properly in the hosted dev enviroment

**Comment by joshhazelhurst123** [comment]
#126 related to this issue?

**Comment by SchaeStewart** [comment]
Sort of. It would be nice if #126 was completed before this issue, but it's
okay if it's not. Just add the variables to the env section of the
docker-compose.yml.

Let me know if you have any questions. You can ask here or ping me on slack

https://bit.ly/cfgso-slack

Thanks!

Schaffer
