### ISSUE TITLE
Decide what candidate information to collect and store

### ISSUE THREAD

**Issue by SchaeStewart** [codeforgso/GoVote#128]
## This is a: 

* [ ] bug
* [ ] enhancement
* [x] feature-discussion

# Feature-Discussion
We need determine what information we want to collect and store for each candidate. We will use this list as a guide for collecting information and for creating a database table for the candidates.

## What we have so far
- This [spreadsheet](https://docs.google.com/spreadsheets/d/1STCIuqDyw1a7wdtX929603SaMrnjuCmaDMujHdlR3IU/edit#gid=393871294) was created at some point and includes fields for social media which I think is a nice thing to have.
- NCSBE provides this [spreadsheet](https://www.ncsbe.gov/Portals/0/Documents/2018_General_Election_Candidate_List_with_Contacts_Updated_08212018.xlsx?ver=2018-08-21-165413-230) with following fields:

Contest Name | Office Type | Contest Title (As Shown on Ballot) | Contest Title Line 2 | Jurisdiction Type | Jurisdiction Value | Candidate Last Name | Candidate First Name | Candidate Middle Name | Candidate Suffix | Name on Ballot | Party | Address | Mailing Address | Home Phone | Office Phone | Business Phone | VRN | VRN County
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

Keeping these fields is probably fine but we also need to add: 

 Website | Facebook | Twitter | LinkedIn | Email | Phone | Incumbent (Yes/No) | Active (Are they still actively running?)
| -- | -- | -- | -- | -- | -- | -- | --

We also need two fields as a way to map candidates to voters. The NCSBE voter registration data contains columns like `nc_senate_abbrv` which contains the value `24` for some voters in Greensboro.  
For each candidate, we need to record what office they are running for (e.g. `nc_senate_abbrv`) and the value of that field (e.g. `24`).  
For now I'll call these fields `contest_to_voter_name` and `contest_to_voter_value`. (I am open to calling these something else if there are any suggestions)  
When recording this information it is imperative that the ` contest_to_voter_name` match the name of a column in the voter registration data. So we will need to provide a list of these field names to contributors.  
Note: The Contest Name is technically already available as a part of the NCSBE candidate data, but adding the information in the manner outlined above should make it easier to retrieve the proper candidates for a given voter.

So in total we have the following:
- Contest Name
- Office Type
- Contest Title (As Shown on Ballot)
- Contest Title Line 2 
- Jurisdiction Type 
- Jurisdiction Value 
- Candidate Last Name 
- Candidate First Name 
- Candidate Middle Name 
- Candidate Suffix 
- Name on Ballot 
- Party 
- Address 
- Mailing Address 
- Home Phone 
- Office Phone 
-  Business Phone 
- VRN 
- VRN County
- Website
- Facebook
- Twitter
- LinkedIn
- Email
- Incumbent
- Active
- contest_to_voter_name
- contest_to_voter_value

**Comment by tleisman** [comment]
This feature is untenable. The datasets provided by the state board of elections do not contain a reliable way to link candidate information with voter registration rolls. Especially for the MVP, we can link to an organization with the infrastructure to support sample ballot creation and candidate information collection such as the League of Women's Voters.
