### ISSUE TITLE
Restructure project to decouple server and client

### ISSUE THREAD

**Issue by SchaeStewart** [codeforgso/GoVote#130]
## This is a: 

* [ ] bug
* [x] enhancement
* [x] feature-discussion
 

# Feature-Discussion
With the current project setup the client are server are coupled together. The project has a single webpack config that bundles everything together. I propose we separate the client and sever for several reasons.

1. By separating the client and server builds we will be separating concerns
2.  We can use `create-react-app` to rebuild the client making future React and webpack upgrades easier.
    1. This would also allow us to use new features like React hooks
3. Separating will make future webpack upgrades easier
4. It could potentially make development easier. We can configure the project in such a way that contributors who are just working on the client can point their client to the dev server instead of a local server

## Implementation
This would be a major change and we will need to proceed with caution. This change will impact the way we are deploying and will require us to change AWS and Travis.  
The change in project structure will also require a change in Docker configuration. However, this will provide us a good opportunity to use Docker for deployment and development. We are currently using Elastic Beanstalk for hosting and this would allow to switch to ECS.

For setting up the new client we can use `create-react-app` then copy our components to the new client folder.

### Resources  

* [An example React/Express project structure](https://medium.com/@maison.moa/setting-up-an-express-backend-server-for-create-react-app-bc7620b20a61)
* [Another example](https://medium.freecodecamp.org/how-to-make-create-react-app-work-with-a-node-backend-api-7c5c48acb1b0)

## Summary
* [x] - Use `create-react-app` and move the client/frontend into its own directory with its own webpack config. **We will not eject the app**
* [x] - Update and reconfigure webpack for the server
* [ ] - Update Docker/Docker-Compose to handle the new project structure and configure Docker for deployment to ECS
* [ ] - Reconfigure AWS/Elastic Beanstalk and Travis to handle new project structure

**Comment by zenlex** [comment]
Now that Docker/AWS seem to be functional with the project as it is and the c-r-a / webpack configs were checked off, it seems like this is no longer an issue....
