### ISSUE TITLE
Setup domain name / DNS

### ISSUE THREAD

**Issue by tcaddy** [codeforgso/GoVote#168]
govotegso.org is registered with Route53 in AWS.

Replace the https://dev-govote-api.herokuapp.com/ URL with this one.

https://devcenter.heroku.com/articles/custom-domains

**Comment by zenlex** [comment]
I think @stevenbuccini  finished this didn't he?

**Comment by zenlex** [comment]
Verify this got stood up on CFA's heroku account? Then need to configure DNS. Currently dig for www / and staging.govote..... both point to our free Heroku account so far. 

There's also an SSL issue with the naked domain
