### ISSUE TITLE
Should we bootstrap the database on every deploy?

### ISSUE THREAD

**Issue by stevenbuccini** [codeforgso/GoVote#178]
## This is a: 

* [ ] bug
* [ ] enhancement
* [x] feature-discussion

# Feature-Discussion
Currently, we drop all tables, create new tables, download data from the state Board of Elections, unzip the data, then load it into the database after _every_ deploy. This seems a little overkill to me. My recommendation would be only run this step manually or control it with a feature flag.

**Comment by zenlex** [comment]
Can we schedule this in the CFA Heroku?

**Comment by tcaddy** [comment]
With the ETL processed being scheduled overnight, we do not need to run this on deploy.
