### ISSUE TITLE
Create City Council election candidate json file.

### ISSUE THREAD

**Issue by marshallj** [codeforgso/GoVote#18]
## This is a: 

* [ ] bug
* [x] enhancement
* [ ] feature-discussion

 

# Enhancement
## Description

Use the City Council Election Candidate spreadsheet [here](https://docs.google.com/spreadsheets/d/15T0VdXd0wOajhbu0jjq3desJrNkjmm4FvhO9JdTnrJ4/edit?usp=sharing) to create a json file that can be queried to show residents' Council Member Information. Json file must meet the following criteria:

We need to be able to query by council district. 

Create a json object for City Council  that has an array of objects for: Mayor, At Large, and ... an array of objects for Council Districts. 

Inside Council District array, create an array of candidates for each district.

**Comment by jadamsnc** [comment]
Any particular folder you want the json file to go in?

**Comment by marshallj** [comment]
Hi Jeremy,
Sorry for the delay. I have been traveling quite a bit lately. Just put it in a ‘data’ folder in the parent directory.

Thanks!

Jason Marshall

**Comment by marshallj** [comment]
Hi @jadamsnc, will you be able to submit the PR for this issue soon? I need to begin creating issues and moving forward with the app functionality that provides the info in the json file. Thanks.

**Comment by jadamsnc** [comment]
Pull request submitted, sorry for the delay.

**Comment by marshallj** [comment]
Awesome @jadamsnc! Thanks for the quick reply. No worries on the delay. We are just trying to get the app in shape for the candidate forum in a couple weeks. We appreciate your contribution.

**Comment by marshallj** [comment]
Done.
