### ISSUE TITLE
Create an 'About' Bootstrap modal to inform users about Code for Greensboro

### ISSUE THREAD

**Issue by marshallj** [codeforgso/GoVote#19]
## This is a: 

* [ ] bug
* [x] enhancement
* [ ] feature-discussion

# Enhancement
## Description

Create an 'About Code for Greensboro' Bootstrap modal that is opened by an 'About' button. Place the button anywhere on the app for now. We can move it once we get to the UI/UX refinements.

See an example of an About Modal from one of our previous projects below:
```
        <Modal show={this.state.showModal} onHide={() => this.setState({showModal:false})}>
          <Modal.Header closeButton>
            <Modal.Title>About Greensboro Finda Facility</Modal.Title>
          </Modal.Header>
          <Modal.Body>
            <p>Finda is a generic "find-a" app for geographic datasets.</p>
            <p><strong>Please send feedback, ideas, and bug reports to our <a href="https://github.com/codeforgreensboro/finda/issues">Github page</a>.</strong></p>

            <hr />

            <h4>About Code for Greensboro</h4>
            <p>We're developers, designers, data nerds, politically-minded people with ideas for making things better, citizens, users of software—in other words, we are this community. We want to use these talents to make Greensboro's government work with the web in new and better ways.</p>

            <p>Feel free to stop by one of our <a href="https://www.bit.ly/cfgrsvp">Bi-weekly Hack Nights</a>, <a href="https://www.github.com/codeforgso">check us out on Github</a>, or <a href="mailto:hello@codeforgreensboro.org">simply drop us a line</a>!</p>

            <hr />

            <h4>Credit Where Due</h4>

            <p>Finda was originally built by <a href="https://github.com/codeforboston">Code for Boston</a>. We stand on the shoulders of giants!</p>

          </Modal.Body>
          <Modal.Footer>
            <a href="http://www.gsobuilt.co" target="_blank">
              <img alt="Built in GSO logo" className="pull-left" src={BuiltInLogo} style={{height:'2.5em'}} />
            </a>
            <Button onClick={() => this.setState({showModal:false})}>Close</Button>
          </Modal.Footer>
        </Modal>
```

**Comment by tuguScript** [comment]
Can I do it?

**Comment by camparker** [comment]
I've actually been working on it, and should be done by this time next week. If anything changes I will let you know.

**Comment by marshallj** [comment]
@tuguScript, let me know if you are interested in contributing to the GoVote project. I need to create another round of issues for the project, and I'm sure we can find one that fits your interest and skills.

**Comment by tuguScript** [comment]
I'm on a vacation. Recently, i have been looking for a react project that I can contribute. I'm available help you guys

**Comment by marshallj** [comment]
Hi @tuguScript are you still interested in working on this issue? Cam has been pulled away and will not be able to complete the issue.

**Comment by kgoooo** [comment]
If tugu doesn't want to / can't take it, I could give it a go!

**Comment by marshallj** [comment]
@kgoooo, go for it. Flagging this issue for you. Thanks!

**Comment by kgoooo** [comment]
Awesome, thank you!!

**Comment by kgoooo** [comment]
Hey @marshallj do you have any copy you want in the About modal or just get it set up and you can add the copy in later?

**Comment by marshallj** [comment]
@kgoooo if you want you can go ahead and set up the modal. I can get the content needed together sometime in the next couple days, and post here for you if that works. If you get the modal done prior, feel free to submit a PR.

**Comment by kgoooo** [comment]
@marshallj that would be great if you could post it here and I can stick it in.  The modal is basically ready to go, I'll just add some finishing touches and ass a PR for how it is without copy.  Thanks!

**Comment by marshallj** [comment]
Hey @kgoooo, finally getting around to this. Hoping you still have some time to work on it. Be sure to pull changes down before proceeding. I moved the About Us button you coded over to the header component and styled it to match the voter info button. See the content for the about modal below:

```
Code for Greensboro works to improve the way our community uses its data and the web. And we need you—no coding required.

We are a local 501(c)(3) organization affiliated with the Code for America Brigade program. Code for America brigades are volunteer civic tech communities that collaborate with local government and community partners to build open source technology websites, and tools. These projects provide greater access to, or augment existing government services, and otherwise help with local civic issues. Code for America supports Brigade chapters with resources, tools, and access to the wider civic technology movement.

We are developers, designers, data nerds, civically-minded people, and residents — in other words, we are this community. We want to use this network and these talents to help local government, and the community create positive impact through technology.

```

In the modal footer, it would be great to have the Code for Greensboro logo that links to codeforgreensboro.org

Thanks!

**Comment by kgoooo** [comment]
@marshallj thanks for the copy and update!  I will try and get to it tomorrow!

**Comment by tuguScript** [comment]
Sorry guys. I was on vacation.

If there is anything, I can help now.

**Comment by marshallj** [comment]
Done. Thanks @kgoooo. @tuguScript, be on the lookout for new issues soon.
