### ISSUE TITLE
Research and design info for the Registration Info Modal

### ISSUE THREAD

**Issue by marshallj** [codeforgso/GoVote#20]
## This is a: 

* [ ] bug
* [x] enhancement
* [ ] feature-discussion

# Enhancement
## Description

The Registration Info Modal appears when a resident's address does not appear in the verify address list. the modal is meant to provide relevant links to information on the North Carolina Elections Board website on how to register to vote, and other relevant info. Research and design the layout of information on the modal to get unregistered or inactive residents the info, or contact info they need to register.

**Comment by kgoooo** [comment]
Hello! I would love to give this a go if possible!

**Comment by marshallj** [comment]
Hi @kgoooo! Thanks for jumping in. Absolutely give this issue a go; I'll assign it to you. 

The placeholder modal is [here](https://github.com/codeforgso/GoVote/blob/master/src/components/RegistrationInfoModal.jsx). We need the content in the issue description pulled together and provided in the modal in an easily consumable design for users. Feel free to remove the content in the modal currently if needed. If you have questions about the needs for this, reach our here. 

The NC Elections Board website is [here](http://www.ncsbe.gov/), and has the webpages you will want to link to. We need to make sure we are linking to the information instead of providing it directly on our page in case the state changes any requirements.

Also, please take a look at our Code of Conduct [here](https://github.com/codeforgso/GoVote/blob/master/.github/CODE_OF_CONDUCT.md)

**Comment by kgoooo** [comment]
@marshallj 
Ok sounds great, thanks for letting me help! 
 I have tried to clone and install this project but keep getting 'Failed at the libpq@1.8.7 install script.' (among other errors)
 I am wondering if it has something to do with my Node?  I'm on 8, but should i move to 6 do you think?

**Comment by marshallj** [comment]
@kgoooo I am on node 8 as well and am able to run the app. Where is this failing for you? and are you using npm or yarn? Also, can you post your stack trace including all errors?

**Comment by kgoooo** [comment]
@marshallj so I realized it was because I didn't have postgresql installed.  Now it will install all the node modules properly, but wont compile with yarn or npm.  Receiving these errors:

> ./src/components/App.jsx
[0]   Line 34:  '_getCouncilDistricts' is not defined       no-undef
[0]   Line 38:  '_getCommissionerDistricts' is not defined  no-undef
[0]   Line 42:  '_getGISData' is not defined                no-undef
[0]   Line 49:  '_getVoterInfo' is not defined              no-undef
[0]   Line 65:  '_validateVoterInput' is not defined        no-undef
[0]   Line 82:  '_showRegInfoModal' is not defined          no-undef
[0]   Line 89:  '_handleInputChange' is not defined         no-undef

**Comment by marshallj** [comment]
@kgoooo good call on the pg install in the readme. 

What version of eslint was installed when you installed the node_modules? If it was 4.x, try forcing an install of v3.19.0.

**Comment by kgoooo** [comment]
@marshallj lint was set to 3.12.0 but upgrading it to 3.19 didn't help unfortunately so I had to make a .eslintignore for src folder, and then I could finally see the page!  Looks cool, tomorrow I'll work on getting the modal set up.  Thanks for the help, sorry it was a pain!

**Comment by marshallj** [comment]
No worries at all @kgoooo, its great to have you contributing! Reach out anytime if you have questions or issues.

**Comment by marshallj** [comment]
@kgoooo you'll need the credentials for our postgres database for the server to work. Send me an email at my address found [here](http://codeforgreensboro.org/leadership), and I'll send you the info.

**Comment by marshallj** [comment]
done. Thanks @kgoooo!
