### ISSUE TITLE
Handle Linting errors

### ISSUE THREAD

**Issue by BlakeGuilloud** [codeforgso/GoVote#30]
## This is a: 

* [x] bug
* [ ] enhancement
* [ ] feature-discussion

 

There are several eslint errors being thrown within the latest App build. Many of them include unnecessary `console.log()`s or missing semi colons.

# BUG

## Expected Behavior

Running `yarn start` and opening your terminal should not return these errors and warnings:

![image](https://user-images.githubusercontent.com/14660993/35893481-3ecceca0-0b7c-11e8-9249-71fed528a4eb.png)

In the case that a `console.log` or `console.error` (printing an error in the console can sometimes be helpful) is useful to the functionality of the app, use the following comment above the line in question:

```
// eslint-disable-next-line no-console
```

**Comment by robatronPrime** [comment]
Hi I would like to help. Is there anything else I need to know before I get started?

**Comment by BlakeGuilloud** [comment]
Hey @robatronPrime ! Sounds great- I will assign the issue to you. If follow the [Readme](https://github.com/codeforgso/GoVote/blob/master/README.md) to get the project running locally, all of these errors and warnings should be printing in your console.

If you want to learn more about eslint rules and how to solve the issues, check out their docs here: https://eslint.org/docs/rules/

Feel free to reach on here or in slack if you have any issues. Thanks!

**Comment by robatronPrime** [comment]
Hi @BlakeGuilloud . I've handled the the errors in my testing environment. Do let me know if anything needs to be changed.
Thanks!

**Comment by BlakeGuilloud** [comment]
Hey @robatronPrime are you still working on this?

**Comment by BlakeGuilloud** [comment]
I am going to go ahead and close this out, as we are moving towards a new development workflow.

Thanks for your attempts at resolving this issue! Stayed tuned for future issues!
