### ISSUE TITLE
Remove pg-native from module dependencies

### ISSUE THREAD

**Issue by SchaeStewart** [codeforgso/GoVote#36]
## This is a: 

* [x] bug
* [x] enhancement
* [ ] feature-discussion
 

# BUG

## Expected Behavior
Dependencies should install without error.

## Current Behavior
If you try installing dependencies without postgressql/libpq installed on the machine the installation fails because pg-native complies from those binaries.

## Possible Solution

Remove pg-native from module dependencies.

## Steps to Reproduce (for bugs)
- In an environment that does not have libpq/postgres installed,
1. Clone the project
2. `npm install` / `yarn install`
3. You should see some errors about pg_config and libpq

## Your Environment

I've tested this on a Windows 10 and Ubuntu Desktop 16.04.

# Enhancement
## Description

By removing pg-native contributors do not have to install postgres/libpq on their machines, making it easier for new contributors to get up and running.
Additionally, since this project only uses a hosted postgres instance, it is not really necessary to use pg-native.

**Comment by BlakeGuilloud** [comment]
Donezo
