### ISSUE TITLE
Automate .etl script.

### ISSUE THREAD

**Issue by BlakeGuilloud** [codeforgso/GoVote#42]
We need to automate our .etl script to run on a cron job that matches the update timer of this data. This can be done via our current EB process, or as a separate process (Lambda function).

I can take charge of this when provided with information surrounding the ncvoter data release cycle.

**Comment by zenlex** [comment]
Needs triage or closure

**Comment by zenlex** [comment]
This is theoretically scheduled and working per @tcaddy  but needs to actually be tested/confirmed.

**Comment by tcaddy** [comment]
I deleted my record in the database on Heroku.  Need to wait until tomorrow to see if it's back.  That'll be proof that the scheduled etl job is really bringing in "new" data.

**Comment by tcaddy** [comment]
Confirmed that scheduled ETL job is working
