### ISSUE TITLE
Map out the data structures for 2018 midterm elections

### ISSUE THREAD

**Issue by SagarMishra** [codeforgso/GoVote#44]
Need to map out (and up) the relationship between the user's address, their precinct, and the other geographical regions that collections of precincts make up.

These regions depend on the specific elections, e.g. county commissioner is an election at the County-level which is a group of certain precincts.

More info here:
https://ballotpedia.org/North_Carolina_elections,_2018

**Comment by SchaeStewart** [comment]
From what I understand there is no feasible way to map this. I'm going to close this issue for now
