### ISSUE TITLE
Errors and Alerts persisting in Voter Lookup Modal

### ISSUE THREAD

**Issue by BlakeGuilloud** [codeforgso/GoVote#50]
There is an issue in our VoterLookup Modal that causes errors / info alerts to persist after the modal has been closed. This leads to an unwanted UX, as closing the modal should refresh the form.

### Steps to reproduce:
- Click "Voter Lookup" to open the VoterLookup modal.
- Do not enter any information for First or Last name.
- Click "Search"
- Errors will throw in the Modal form.
- Click "Close"
- Click the "Voter Lookup" modal again, and the errors will still exist.

**After following the above steps:**

![image](https://user-images.githubusercontent.com/14660993/37749965-df6913ea-2d60-11e8-9942-e3a85e87872d.png)

There is an issue that goes in hand with this:

After triggering "No Voter Registration Info Found" feedback by entering a voter name that is not found. I.E. First Name: "Leslie", Last Name: "Knope", and then closing the Modal as mentioned above, the "No Voter Registration Info Found" warning will persist:

![image](https://user-images.githubusercontent.com/14660993/37750083-7652c044-2d61-11e8-8b2d-62115ece9870.png)

### Acceptance Criteria
- Upon dismissing the Voter Lookup Modal, all Errors and Feedback should be cleared.
- All ESLint rules are passing.

**Comment by SchaeStewart** [comment]
Hey, that's awesome! Contact us on [slack](https://slack.codeforgreensboro.org) in the proj-govote channel, if you need any help

**Comment by BlakeGuilloud** [comment]
Hey @mrcolo ! Just checking in to make sure you are still interested in this issue?

**Comment by mrcolo** [comment]
Hey! Sorry for the lag. I've tried to edit the React components, but error still show up. I am glad somebody was able to solve the issue!

**Comment by BlakeGuilloud** [comment]
No problem @mrcolo ! We had our Community Action Night tonight and one of the attendees was able to solve it.

**Comment by mrcolo** [comment]
Maybe I should work on something a little more basic. I am familiar with React but I still have issues when it comes to very specific bugs. @BlakeGuilloud Let me know if there's anything else I can help with!
