### ISSUE TITLE
CSS Preprocessor

### ISSUE THREAD

**Issue by BlakeGuilloud** [codeforgso/GoVote#51]
We should investigate an appropriate CSS Preprocessor to bring into the GoVote project, and implement it. 

From a strict preprocessor standpoint, the two most well supported options are [Sass](https://sass-lang.com/) and [Less](http://lesscss.org/). I am open to either of these.

While non-conventional, the subject of CSS in JS is gaining traction lately, so we could also potentially invest this project into something like [Styled Components](https://www.styled-components.com/), which I love!

### Acceptance Criteria
Regardless of the library chosen, the implementation should:
- Integrate with our hot-reloading development environment (i.e. if I make a change to a .scss/.less/.js file, the browser reloads automatically)
- Move appropriate CSS to respective styling files.
- Organize our styles into an appropriate directory.

**Comment by curleypg** [comment]
PR incoming. Let me know if there are additional requirements.

**Comment by remrobem** [comment]
@curleypg Hey Philip - thanks for the PR. We were looking at implementing Sass, with .scss,  in the project following the steps in [(https://medium.com/@oreofeolurin/configuring-scss-with-react-create-react-app-1f563f862724)]
Can you help us understand advantage of node-saas-chokidar vs method outlined in link?

**Comment by remrobem** [comment]
OK - thanks Philip. I will read some more about it and test it out. And thanks for assisting on the project.

**Comment by remrobem** [comment]
@SchaeStewart  I recommend we implement the PR from Philip. The changes he made using node-sass-chokidar will provide performance improvements in the docker environment. It makes use of https://github.com/paulmillr/chokidar. After this is merged with your changes, we will need to refactor the scss files to make full use of Sass

**Comment by SchaeStewart** [comment]
@remrobem When I merged the PR the site crashed. Do you want to pull it in and take a look at it?
