### ISSUE TITLE
Loading state for Form Submission

### ISSUE THREAD

**Issue by BlakeGuilloud** [codeforgso/GoVote#52]
The Voter Lookup Modal should provide a visual indicator that the form has been submitted and the request is processing. Currently, upon clicking the "Search" button from within VoterInfoForm, there is no indication that the request is processing, thus leading to a poor user experience. We should implement a "Loading" state of some sort to give the user feedback that their request for lookup has been made.

### Steps to Reproduce
- Enter a first and last name after clicking "Voter Lookup"
- Submit the form

There is a decent amount of time that passes while our API is looking up a proper response, so we need to let our users know.

### Acceptance Criteria
- Upon submitting a form via Voter Lookup, the "Search" button indicates that the form is "in progress".

The way this is implemented is up to the author, but suggestions would be to Disable the state of the button while the form is process or to look into animating a [Glyphicon](https://getbootstrap.com/docs/3.3/components/#glyphicons).

**Comment by ethangk** [comment]
I'm happy to take a look at this!
