### ISSUE TITLE
Refactor to incorporate project config from create-react-app

### ISSUE THREAD

**Issue by marshallj** [codeforgso/GoVote#6]
## This is a: 

* [ ] bug
* [x] enhancement
* [ ] feature-discussion

# Enhancement
## Description

implement the react-scripts package to handle the configuration of this project.

**Comment by BlakeGuilloud** [comment]
After conversations with Jason. I have decided to pursue the option of using the [react-scripts](https://www.npmjs.com/package/react-scripts) package to handle the configuration of this project. By default the package supplies it's config in the package itself; however, there is an option to eject this configuration into the project locally, which gives us the opportunity to customize and tailor the webpack configuration to our specific needs.

While this option is being explored, I am not shutting out the idea of building our webpack config from scratch as the currently project uses.

I will have a solution and a PR up by the end of the week.

**Comment by marshallj** [comment]
done
