### ISSUE TITLE
Mockups

### ISSUE THREAD

**Issue by BlakeGuilloud** [codeforgso/GoVote#60]
Placeholder issue for mockup discussion / sharing.

**Comment by SagarMishra** [comment]
so we did some design work last meeting and the notes are in the Wiki (https://github.com/codeforgso/GoVote/wiki). @SchaeStewart and @tleisman are working on creating github issues for the technical and non-technical components of this design, so keep an eye out on the issues list as we might be breaking up the mockups tasks into smaller pieces.
