### ISSUE TITLE
Collect Candidates Information

### ISSUE THREAD

**Issue by SchaeStewart** [codeforgso/GoVote#66]
We need to collect information on candidates running in the upcoming elections.

## Upcoming Elections
We need candidate info for the following elections:
- Guilford County Commissioner
- Board of Education Districts (as of January 2016)
- NC State House Districts (newly redistricted for the 2018 elections)
- NC State Senate Districts (newly redistricted for the 2018 elections)
- Guilford County Superior Court Districts
- US House of Representatives

## Desired Info
- Name
- District
- Website
- Facebook
- Twitter
- LinkedIn
- Email
- Phone
- Incumbent (Yes/No)
- Active (Are they still actively running?)

**Comment by tleisman** [comment]
We need a section for the constitutional amendments as well. 

This is a google sheet where we can all contribute information about candidates and referendums/amendments. Please comment here after you enter something so we can all keep up!

https://docs.google.com/spreadsheets/d/1STCIuqDyw1a7wdtX929603SaMrnjuCmaDMujHdlR3IU/edit?usp=sharing

**Comment by tleisman** [comment]
Added amendment information from here: https://www.newsobserver.com/news/politics-government/article216437935.html

**Comment by tleisman** [comment]
Steven recommends emailing the parties to get candidate lists.

**Comment by SchaeStewart** [comment]
This document on page 120 lists a lot of the candidates. https://www.ncsbe.gov/Portals/0/Documents/2018_General_Election_Candidates_with_Contacts.pdf

We will still need to collect social media information

**Comment by tleisman** [comment]
If we can't link candidate information to voter registration in time for MVP release, we may just want to change this to "What's At Stake" with some copy and links, like:

In 2018, you will be voting on your local candidates as well as proposed amendments to the state constitution. 

To view your local candidates, go here and follow the instructions: https://www.ncvoter.org/your-ballot-and-precinct/

To view more information about the constitutional amendments, go here: https://www.ncsbe.gov/Elections/2018-Election-Information

**Comment by SchaeStewart** [comment]
We've decided to not store and display candidate information because of the level of difficulty involved
