### ISSUE TITLE
Filter out removed voters addresses' from Voter Lookup

### ISSUE THREAD

**Issue by SchaeStewart** [codeforgso/GoVote#73]
## This is a: 

* [x] bug
* [ ] enhancement
* [ ] feature-discussion

 

# BUG

## Expected Behavior
Addresses that say "REMOVED" should not be displayed to the users.

## Current Behavior
Voters whose info has been removed by the state board of elections is being returned by the API and is displayed to the users.

## Possible Solution

- In server.js filter out results where `voter_status_desc` is `REMOVED`.

## Steps to Reproduce (for bugs)

1. Look up voter info for  `John Smith`
2. There will be several addresses they say "REMOVED"

**Comment by rtrunkhill** [comment]
HI, I'd like to help with this one.  I'll fork and get it started on it right away

**Comment by SchaeStewart** [comment]
@rtrunkhill Awesome! Check the Contributing guide for help getting started and if you have any questions ping you can ping us on slack.

**Comment by rtrunkhill** [comment]
im getting an error when i make any changes to the WHERE clause.  Can i get an invite to Slack Channel?  Same name @gmail.com

**Comment by SchaeStewart** [comment]
@rtrunkhill you can get register for the slack [here](http://slack.codeforgreensboro.org/)

**Comment by SchaeStewart** [comment]
@rtrunkhill Your PR has been merged. Thank you so much for contributing!
