### ISSUE TITLE
Create Copy for Home Page

### ISSUE THREAD

**Issue by SchaeStewart** [codeforgso/GoVote#79]
## This is a: 

* [ ] bug
* [x] enhancement
* [ ] feature-discussion

# Enhancement
## Description

Create some informational text for the home page that includes information about the project and our mission statement.

## Implementation

Here is our current mission statement:  
>The goal of GoVoteGSO project is to create a web application that the local public can use to easily view their voter registration information and election candidate information.  
Use this as a reference for the homepage copy. Try to keep jargon and technical terms out of the final result.

**Comment by SagarMishra** [comment]
some ideas:
"Let Your Voice Be Heard: Go Vote!"
"Your Vote is Your Voice: Go Vote!"

the various menu buttons we described should themselves be labeled with very self-explanatory text about what to do next (i.e. "Where do I vote?", "Who can I vote for?", etc)

**Comment by tleisman** [comment]
I created some simple copy here: https://docs.google.com/document/d/19M7lxyxkiYohu-YcdIahd7oA2pYY58TuE5oRPIUHgvY/edit?usp=sharing

This is a good starting point and gives us more than a placeholder. Recommend we get a logo designed to have some inviting art or at least a simple banner when people sign on.
