### ISSUE TITLE
Identify a source for geojson data layers.

### ISSUE THREAD

**Issue by marshallj** [codeforgso/GoVote#8]
## This is a: 

* [ ] bug
* [ ] enhancement
* [x] feature-discussion

 

# Feature-Discussion

 We need to identify a source for the geojson layers listed below. Ideally we will need to access the data via an API. Locate a source for the GIS data listed below:

-   School Board
-   Superior Court Districts
-   NC House of Rep. Districts 
-   NC Senate Districts
-   US Congress Districts
-   Polling Places
-   Voting Precincts
-   Early Voting Places

**Comment by jasonajones73** [comment]
I have downloaded shapefiles for School Board, Superior Court, NC House, NC Senate, GSO City Council, HP City Council, and County Commissioners. All have been converted to GeoJSON and posted to County data portal under CfG organization for programmatic access. I will also create an organization account for Jason Marshall on the county data portal. I am pretty sure I can quickly get polling places and early voting places.

**Comment by marshallj** [comment]
Complete for now. Closing.
