### ISSUE TITLE
Add Map to Home page

### ISSUE THREAD

**Issue by SchaeStewart** [codeforgso/GoVote#80]
## This is a: 

* [ ] bug
* [x] enhancement
* [ ] feature-discussion

# Enhancement
## Description

While restructuring the project and implementing react-router, the map was removed from the app.  
The map may be removed or relocated later, but for now it needs to be added back to the home page.

## Implementation

Look at previous commits that used the map for implementation ideas. If possible/necessary move the state into the map component/MapContainer and keep it out of the home page.

**Comment by vatdaell** [comment]
Hi,
I can work on this feature if no one is working on it.

**Comment by SchaeStewart** [comment]
@vatdaell That's awesome, I'll add you to the slack and you can message us if you have any issues

Thanks so much!

**Comment by vatdaell** [comment]
@SchaeStewart  that's great, is there a slack link that I can follow

**Comment by SchaeStewart** [comment]
@vatdaell https://join.slack.com/t/cfgso/shared_invite/enQtMzk4NTIzNjAzMjA0LWQwMzdiZWZjZjUxNDUyNjgxY2EwNjg1OGY2NzgwOTQ2NDY1MmE3MzY1NTVhZjUzM2Q1MDU5ZGQ4NTkzNGI2MzQ

**Comment by SchaeStewart** [comment]
No longer placing map on homepage. Closing issue now.
