### ISSUE TITLE
Collect dates for upcoming elections

### ISSUE THREAD

**Issue by SchaeStewart** [codeforgso/GoVote#81]
## This is a: 

* [ ] bug
* [x] enhancement
* [ ] feature-discussion

# Enhancement
## Description

Collect dates for upcoming elections in Greensboro/Guilford county. Include Election Day and Early Voting for each election

Early Voting: Thursday, October 18 - Saturday, November 3
Election Day: Tuesday, November 6, 2018

As of 6/26/18, the exact early voting schedule isn't available.

**Comment by spham3** [comment]
I can look into this.

**Comment by SchaeStewart** [comment]
Election is over. Closing issue
