### ISSUE TITLE
Voter registration information

### ISSUE THREAD

**Issue by tleisman** [codeforgso/GoVote#85]
## This is a: 

* [ ] bug
* [x] enhancement
* [ ] feature-discussion

 

We need information about the voter registration process in North Carolina and a "how to" guide for non-registered voters (or those who need to update their voter registration address).

**Comment by svcharles** [comment]
**Google Docs on Voter Registration in NC**

https://docs.google.com/document/d/1b_706NXPCn8JXiHz5gsV5gvOyjoG0ZdH3-Lz60ueVGU/edit?usp=sharing
