### ISSUE TITLE
Data Validation for the Voter Registration lookup.

### ISSUE THREAD

**Issue by marshallj** [codeforgso/GoVote#9]
## This is a: 

* [ ] bug
* [x] enhancement
* [ ] feature-discussion

 

# Enhancement
## Description

Implement data validation on the first name and last name text inputs in the voter modal. Enforce a value in both text inputs. Take a look at the React-Bootstrap validation tools. Reach out to @marshallj with questions, and to verify direction.

**Comment by marshallj** [comment]
@SchaeStewart are you still working on this issue? If not, let me know and I'l reassign. Thanks!

**Comment by SchaeStewart** [comment]
@marshallj I am still working on it. I should have PR sometime tomorrow

**Comment by marshallj** [comment]
Complete. Thanks @SchaeStewart!
