### ISSUE TITLE
Day of Info - What To Expect

### ISSUE THREAD

**Issue by SchaeStewart** [codeforgso/GoVote#98]
## This is a: 

* [ ] bug
* [x] enhancement
* [ ] feature-discussion

# Enhancement
## Description

Generate content for the Day Of Info page about what to expect. [Vote411](http://www.vote411.org/) has a lot of good info which we can link to, but we should also provide any other info voters often have questions about.

**Comment by tleisman** [comment]
Some political issues affect this - last I heard, they're still working out what the hours for early voting will be. But we can start filling this in with information about election day itself. One source would be here: http://www.ncvoter.org/voting-in-nc/#one

**Comment by tleisman** [comment]
When you show up to your polling place on the day of voting (and even at some popular places during early voting!), you can expect to see people handing out flyers standing near the entrance to the building in which voting takes place. These are usually volunteers with campaigns or a political party and they are allowed to hand out literature, but not heckle you or hand out literature within a certain distance of the entrance. Depending on how popular your polling place is, there may be many or just a few of these volunteers.

When you enter the polling place, you will be asked for your name so the poll workers can check you off the list of registered voters. You are not allowed to solicit with literature or bring any large/disruptive campaign materials into the polling place. There may be a line, especially depending on the time of day you show up to vote. A poll worker will call you forward once it's your turn to use one of the touchscreen voting machines; making your selection is easy and a paper receipt will register your choices as you make them, creating an audible sound similar to a cash register. 

The entire process is fairly straightforward and should not require much time or effort. If your right to vote is threatened or hampered in any way, even if by means besides direct violence or intimidation, PLEASE call 1-866-OUR-VOTE or visit https://866ourvote.org/ to report the disruption!

**Comment by tleisman** [comment]
Covered with the copy in issue #145
